### ISSUE TITLE
Sometimes chunks are not saved

### ISSUE THREAD

**Issue by artur9010** [InfernalSuite/AdvancedSlimePaper#84]
**Describe the issue**

After gracefully stopping server (/stop) and starting it again some chunks was not saved. I didn't seen any errors in logs.

![image](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/4835677/3588d83f-cce7-4f95-a518-86303d852542)

**Spigot version**
Build 1436 from Discord. I also tried to edit map on purpur fork - same issue.

**Plugin version**
as above

**Comment by emmanuelvlad** [comment]
my PR https://github.com/InfernalSuite/AdvancedSlimePaper/pull/56 should fix this issue

**Comment by emmanuelvlad** [comment]
When chunk gets unloaded it will replace the in memory chunk with a `SlimeChunkSkeleton`
Mutating a loaded "unloaded" chunk will have no effect when saving the world because the chunk is referencing the `SlimeChunkSkeleton`
Getting further from the loaded chunk will call the `unload` method which will replace the in memory chunk, thus saving the chunk state properly.

To sum up, unloaded chunks that gets loaded back will not reflect the chunk in the save until it gets unloaded again.
Commenting `SlimeInMemoryWorld.java:115` resolves this issue, but could it have any side effects?


**Semi related issue:** Spawning on a world (`PlayerSpawnLocationEvent`) makes the chunk (on which the player spawned) unload

**Comment by kyngs** [comment]
Fixed in https://github.com/InfernalSuite/AdvancedSlimePaper/commit/cb50193868308739db2b21776c119d3f490e234e
